### ISSUE TITLE
Youtube Whitelist

### ISSUE THREAD

**Issue by mholtstrom** [jaredh159/safetube#1]
@jaredh159 I'm a developer who wants to configure his 7-year-old's ChromeBook (that is controlled via FamilyLink) to only be able to browse and play videos based on a whitelist of channels (like TedEd). From my investigation so far, this isn't supported by Google/Chromebook/FamilyLink/YouTube. A chrome extension seems like my best bet. My full analysis is at https://holtstrom.com/michael/blog/post/735/Internet-for-Kids.html And you can reach me at [chromeapps at holtstrom.com] It looks like you started on this but abandoned it 4 years ago. If you have any advice for me in building my own version, I'd appreciate it.

**Comment by jaredh159** [comment]
@mholtstrom hi there.  to be honest i forgot about this repo, must have been an experiment, i don't think i ever got a chrome extension working. i did make a simple little youtube embed website that disables some features, and i used that whenever i had to link my computer students to a specific youtube video, like this:

https://htc-viewer.netlify.app/?id=zTi3_l5h5PQ

it's nothing much, but it kept the youtube sidebar away, and made the suggestions restricted to the channel of the video i linked them to. source code for that is on a private gitlab, but i could get it to you, if you wanted it, although there's not much too it.

i read your blog post, and i felt a little encouraged by it, it's nice to find other parents taking this sort of thing seriously. it's super important and often neglected.

in case it's interesting to you, although i didn't get a chrome extension working, what i did do is a couple years ago I wrote my own macOS parental controls app, because i wasn't satisfied with anything i could find on the market. it's only for macOS, and it's not for everyone (geared towards those inclined to be pretty strict/careful with their kids), but you might find it interesting, if you have a mac computer your daughter can use. here's the url: https://gertrude.app/ 

it doesn't have a youtube whitelist feature (although i've nearly started work on that feature several times, and might still). but it has some other features that sorta make up for the lack. for example, my kids often need to watch some youtube videos for schoolwork, but i don't want to unblock youtube, so i use Gertrude with all of them, when they need to watch a youtube video, they send me a filter suspension request for some number of minutes, and tell me what they're going to watch. i approve it, and Gertrude takes screenshots of them while the filter is suspended, so i can see that they only watched that video, and they know i'll see it if they watch anything else.  not perfect, but works pretty well for my family, fwiw.

**Comment by mholtstrom** [comment]
@jaredh159 Thanks for the detailed reply. A chrome extension will work best in my case since she's using ChromeOS and many educational sites embed YouTube videos. I'll probably use or fork one of the extensions mentioned in my post. But thanks again for the info.
